#!/usr/bin/env python3
"""
inspect_inputs.py — Inspect all raw input files and document their schemas.
Writes reference_data/input_inventory.md with actual column names and sample data.
Run this BEFORE any generation logic.
"""
import os, sys, json, csv
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
DATA_RAW = BASE.parent / "data" / "raw"
REF = BASE / "reference_data"
REF.mkdir(exist_ok=True)

SANCTIONS_DIR = DATA_RAW / "sanctions"
PEPS_DIR      = DATA_RAW / "peps"
KEGGLE_DIR    = DATA_RAW / "keggle"

lines = ["# Input Inventory\n", f"Generated by inspect_inputs.py\n\n"]

def section(title):
    lines.append(f"## {title}\n\n")

def log(msg):
    print(msg)
    lines.append(msg + "\n")

# ── 1. sanctions/targets.simple.csv ──────────────────────────────────────────
section("1. sanctions/targets.simple.csv")
sanctions_csv = SANCTIONS_DIR / "targets.simple.csv"
if sanctions_csv.exists():
    log(f"Path: {sanctions_csv}")
    log(f"Size: {sanctions_csv.stat().st_size / 1e6:.1f} MB")
    with open(sanctions_csv, "r", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames
        log(f"Columns ({len(cols)}): {cols}")
        rows = []
        for i, row in enumerate(reader):
            if i >= 5: break
            rows.append(row)
        log(f"Sample row keys present: {list(rows[0].keys()) if rows else 'N/A'}")
        for k, v in (rows[0].items() if rows else {}.items()):
            log(f"  {k!r}: {repr(v[:80]) if v else repr(v)}")
    lines.append("\n")
else:
    log(f"MISSING: {sanctions_csv}")

# ── 2. sanctions/entities.ftm.json ───────────────────────────────────────────
section("2. sanctions/entities.ftm.json")
ftm_json = SANCTIONS_DIR / "entities.ftm.json"
if ftm_json.exists():
    log(f"Path: {ftm_json}")
    log(f"Size: {ftm_json.stat().st_size / 1e6:.1f} MB")
    with open(ftm_json, "r", encoding="utf-8", errors="replace") as f:
        first_char = f.read(1)
        f.seek(0)
        import ijson
        if first_char == "[":
            log("Format: JSON array")
            f.seek(0)
            entities = []
            for entity in ijson.items(f, "item"):
                entities.append(entity)
                if len(entities) >= 3:
                    break
        elif first_char == "{":
            log("Format: concatenated JSON objects (JSON stream)")
            f.seek(0)
            entities = []
            # ijson supports multiple_values for concatenated JSON objects
            try:
                for entity in ijson.items(f, "", multiple_values=True):
                    entities.append(entity)
                    if len(entities) >= 3:
                        break
            except Exception as e:
                log(f"  ijson multiple_values failed: {e}, trying manual split")
                f.seek(0)
                raw = f.read(50000)
                # Find record boundaries: }\n{
                parts = raw.split('\n{')
                for i, part in enumerate(parts[:3]):
                    if i > 0:
                        part = '{' + part
                    # Find end of this object
                    try:
                        entities.append(json.loads(part.rstrip().rstrip(',')))
                    except:
                        try:
                            # incomplete, try finding closing }
                            obj_end = part.rfind('}')
                            if obj_end > 0:
                                entities.append(json.loads(part[:obj_end+1]))
                        except:
                            pass
        else:
            log(f"Format: unknown (first char: {repr(first_char)})")
            entities = []
    if entities:
        e0 = entities[0]
        log(f"Top-level keys: {list(e0.keys())}")
        log(f"Schema field: {e0.get('schema', 'N/A')}")
        props = e0.get("properties", {})
        log(f"Properties keys (sample): {list(props.keys())[:15]}")
        for i, ent in enumerate(entities[:5]):
            log(f"Entity {i}: id={ent.get('id')}, schema={ent.get('schema')}")
    # Also scan more entities to see relationship schemas
    log("Scanning first 5000 lines for relationship schemas...")
    rel_schemas = {}
    with open(ftm_json, "r", encoding="utf-8", errors="replace") as f2:
        buf = []
        for i, line in enumerate(f2):
            if i > 5000:
                break
            if line.startswith('{') and buf:
                try:
                    obj = json.loads('\n'.join(buf))
                    sc = obj.get('schema', '')
                    rel_schemas[sc] = rel_schemas.get(sc, 0) + 1
                except:
                    pass
                buf = [line.rstrip()]
            else:
                buf.append(line.rstrip())
        if buf:
            try:
                obj = json.loads('\n'.join(buf))
                sc = obj.get('schema', '')
                rel_schemas[sc] = rel_schemas.get(sc, 0) + 1
            except:
                pass
    log(f"Schema distribution (first 5k lines): {dict(sorted(rel_schemas.items(), key=lambda x: -x[1])[:20])}")
    log("FTM format: multi-line JSON objects, each starting with '{' at column 0")
    log("Streaming approach: accumulate lines, emit when new '{' at col 0 is seen")
    lines.append("\n")
else:
    log(f"MISSING: {ftm_json}")

# ── 3. sanctions/pairs-20251209.json ─────────────────────────────────────────
section("3. sanctions/pairs-20251209.json")
pairs_json = SANCTIONS_DIR / "pairs-20251209.json"
if pairs_json.exists():
    log(f"Path: {pairs_json}")
    log(f"Size: {pairs_json.stat().st_size / 1e6:.1f} MB")
    with open(pairs_json, "r", encoding="utf-8", errors="replace") as f:
        first_char = f.read(1)
        f.seek(0)
        import ijson
        if first_char == "[":
            log("Format: JSON array")
            items = []
            for item in ijson.items(f, "item"):
                items.append(item)
                if len(items) >= 3:
                    break
        elif first_char == "{":
            log("Format: NDJSON or concatenated JSON")
            # Try NDJSON first (single-line objects)
            items = []
            for line in f:
                line = line.strip()
                if line and line.startswith('{'):
                    try:
                        items.append(json.loads(line))
                    except json.JSONDecodeError:
                        # Multi-line format, try ijson multiple_values
                        break
                if len(items) >= 3:
                    break
            if not items:
                f.seek(0)
                for item in ijson.items(f, "", multiple_values=True):
                    items.append(item)
                    if len(items) >= 3:
                        break
        else:
            log(f"Format: unknown (first char: {repr(first_char)})")
            items = []
    if items:
        log(f"Top-level keys of item 0: {list(items[0].keys())}")
        log(f"Sample item 0: {json.dumps(items[0], default=str)[:400]}")
        log(f"Sample item 1: {json.dumps(items[1], default=str)[:400]}")
    lines.append("\n")
else:
    log(f"MISSING: {pairs_json}")

# ── 4. peps/targets.simple.csv ───────────────────────────────────────────────
section("4. peps/targets.simple.csv")
peps_csv = PEPS_DIR / "targets.simple.csv"
if peps_csv.exists():
    log(f"Path: {peps_csv}")
    log(f"Size: {peps_csv.stat().st_size / 1e6:.1f} MB")
    with open(peps_csv, "r", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames
        log(f"Columns ({len(cols)}): {cols}")
        rows = []
        for i, row in enumerate(reader):
            if i >= 5: break
            rows.append(row)
        if rows:
            for k, v in rows[0].items():
                log(f"  {k!r}: {repr(v[:80]) if v else repr(v)}")
    lines.append("\n")
else:
    log(f"MISSING: {peps_csv}")

# ── 5. keggle/HI-Small_Trans.csv ─────────────────────────────────────────────
section("5. keggle/HI-Small_Trans.csv")
hi_trans = KEGGLE_DIR / "HI-Small_Trans.csv"
if hi_trans.exists():
    log(f"Path: {hi_trans}")
    log(f"Size: {hi_trans.stat().st_size / 1e6:.1f} MB")
    with open(hi_trans, "r", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames
        log(f"Columns ({len(cols)}): {cols}")
        rows = []
        for i, row in enumerate(reader):
            if i >= 5: break
            rows.append(row)
        if rows:
            for k, v in rows[0].items():
                log(f"  {k!r}: {repr(v[:80]) if v else repr(v)}")
    lines.append("\n")
else:
    log(f"MISSING: {hi_trans}")

# ── 6. keggle/HI-Small_Patterns.txt ─────────────────────────────────────────
section("6. keggle/HI-Small_Patterns.txt")
hi_patterns = KEGGLE_DIR / "HI-Small_Patterns.txt"
if hi_patterns.exists():
    log(f"Path: {hi_patterns}")
    log(f"Size: {hi_patterns.stat().st_size / 1024:.1f} KB")
    with open(hi_patterns, "r", encoding="utf-8", errors="replace") as f:
        for i, line in enumerate(f):
            if i >= 15: break
            log(f"  Line {i}: {line.rstrip()}")
    lines.append("\n")
else:
    log(f"MISSING: {hi_patterns}")

# ── 7. keggle/HI-Small_accounts.csv ─────────────────────────────────────────
section("7. keggle/HI-Small_accounts.csv")
hi_accounts = KEGGLE_DIR / "HI-Small_accounts.csv"
if hi_accounts.exists():
    log(f"Path: {hi_accounts}")
    log(f"Size: {hi_accounts.stat().st_size / 1e6:.1f} MB")
    with open(hi_accounts, "r", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        cols = reader.fieldnames
        log(f"Columns ({len(cols)}): {cols}")
        rows = []
        for i, row in enumerate(reader):
            if i >= 3: break
            rows.append(row)
        if rows:
            for k, v in rows[0].items():
                log(f"  {k!r}: {repr(v[:80]) if v else repr(v)}")
    lines.append("\n")
else:
    log(f"MISSING: {hi_accounts}")

# ── Write inventory ───────────────────────────────────────────────────────────
out = REF / "input_inventory.md"
out.write_text("".join(lines), encoding="utf-8")
print(f"\nWrote {out}")
